name = "rcerrud/nativetokens"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'rcerrud/nativetokens'"

[repository]
user = "rcerrud"
project = "nativetokens"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.2.0"
source = "github"
